import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Res from "@/components/home/nav/Res";
import Footer from "@/components/home/footer/Footer";

const geistSans = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web dev pofo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Res></Res>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
